# Generated by Django 5.2.7 on 2025-10-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0003_busroute_assignment_bulletin_buslocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
