# Generated by Django 5.2.7 on 2025-10-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0004_payment_account_number_payment_ifsc_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('college_type', models.CharField(blank=True, max_length=100)),
                ('placement_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_package', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('highest_package', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hostel_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tuition_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admission_process', models.TextField(blank=True)),
                ('courses_offered', models.TextField(blank=True)),
                ('facilities', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'College Information',
                'ordering': ['name'],
            },
        ),
    ]
